### ISSUE TITLE
Question about this library

### ISSUE THREAD

**Issue by ranhsd** [team-supercharge/boa#4]
Hi, 
i wanted to know if this library is still maintained or not? 
I am asking because i use it today and noticed that swift3 is not supported ... 

Thanks.

**Comment by exoszajzbuk** [comment]
Hi @ranhsd 

We're working on the Swift 3 support, and will keep you posted when it's done.

Best,
Balazs

**Comment by ranhsd** [comment]
Ok, thanks!

**Comment by davidkovaccs** [comment]
Hey @ranhsd, We've just merged the changes so now you can use it also with Swift 3.0 or 3.1!
